# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 11f6b22af88375128458dea0f4e2f633e675915a28d828664653470e4d5c5e1a70d1d61fbe26ba18b8cbb7715bee1147981d607359daeeabb9a19c585736caa3

test:
  secret_key_base: 8c354c65d6c8af17f9920fa289ddfa76ceb43abdc787d6e397c2f2e6a1cd875eb654b67bd41c1c9bce1b1790e2e973e3c7c4cea4498fdcf3f1d92bdd6dc8de72

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
